### ISSUE TITLE
Quiz-abbrechen-Funktion erstellen

### ISSUE THREAD

**Issue by flow85** [erbsenhirn/CoroQuiz#6]

**Comment by LeonieEbert** [comment]
Home-Button zum Quizabbrechen wurde hinzugefügt. Bislang wurde wird aber noch nicht gefragt, ob man wirklich das Quiz abbrechen möchte, sondern man gelangt direkt zum Startmenü. Ebenso wurde der Home-Button beim Ergebnis und bei den Hintergrundinfos hinzugefügt.

**Comment by erbsenhirn** [comment]
Quiz zurücksetzen und vorher Abfrage, ob man wirklich abbrechen möchte
